### ISSUE TITLE
input() at the end?

### ISSUE THREAD

**Issue by gabru-md** [Pranav-Rastogi/barbell-lift#1]
why do you put input(STRING) at the end of every program?

```sh
input("\n\nPress enter to exit.")
```
XD

**Comment by Pranav-Rastogi** [comment]
So that if you run the program with a  double click, the screen stays untill you press <kbd>enter</kbd>. Its like the `getch()` in C++. Just to hold the screen.

**Comment by gabru-md** [comment]
is it just me or the snippet to predict is missing?

**Comment by gabru-md** [comment]
```sh
clf = clf.fit(x,y) 
clf.predict(PREDICTION_DATA)
```
^^^^

**Comment by Pranav-Rastogi** [comment]
The [k-fold cross-validation](https://en.wikipedia.org/wiki/Cross-validation_(statistics)#k-fold_cross-validation) method automatically splits the dataset and scores the learning method used.

Moreover, the user will most probably not have data from 52 accelerometers and hence a snippet to take input from user and predict will not be a very good idea.

The computation of predictions for the purpose of scoring has already been taken care of by the `cross_val_score` method.
